global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'uam_app'
    metrics_path: '/metrics'
    static_configs:
      # host.docker.internal resolves to the host machine where the Go app is running (port 8080)
      - targets: ['host.docker.internal:8080']
